services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: chari-u-website
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./:/usr/share/nginx/html
